export default {
    viewTypes: {
        day: 'day',
        week: 'week',
        month: 'month',
    },
    calendarCategories: [
        {
            id: 'live-stream',
            name: 'LIVE STREAM',
            color: '#ffffff',
            backgroundColor: '#6441a5',
            dragBackgroundColor: '#7d5bbe',
            borderColor: '#4b2e83',
        },
        {
            id: 'podcast',
            name: 'PODCAST',
            color: '#ffffff',
            backgroundColor: '#ff4b2b',
            dragBackgroundColor: '#ff6f61',
            borderColor: '#c70039',
        },
        {
            id: 'personal',
            name: 'Personal',
            color: '#333333',
            backgroundColor: '#ffe066',
            dragBackgroundColor: '#ffd700',
            borderColor: '#e1ad01',
        },
        {
            id: 'travel',
            name: 'Travel',
            color: '#ffffff',
            backgroundColor: '#00b4d8',
            dragBackgroundColor: '#48cae4',
            borderColor: '#0077b6',
        },
        {
            id: 'special-holiday',
            name: 'Special Holiday',
            color: '#ffffff',
            backgroundColor: '#ff6f61',
            dragBackgroundColor: '#ffb4a2',
            borderColor: '#c70039',
        },
        {
            id: 'etc',
            name: 'etc',
            color: '#ffffff',
            backgroundColor: '#929292',
            dragBackgroundColor: '#bdbdbd',
            borderColor: '#616161',
        },
    ],
    exampleEvents: [
        {
            id: '1',
            calendarId: 'podcast',
            title: 'Genshin',
            body: 'TOAST UI Calendar',
            start: '2025-08-01T10:00:00',
            end: '2025-08-01T11:00:00',
            location: 'Meeting Room A',
            attendees: ['A', 'B', 'C'],
            category: 'time',
            state: 'Free',
            isReadOnly: false,
            color: '#6441a5',
            customStyle: {
                fontStyle: 'italic',
                fontSize: '15px',
            },
        },
        {
            id: '2',
            calendarId: 'live-stream',
            title: 'Battlefield',
            body: 'TOAST UI Calendar',
            start: '2025-08-01T17:00:00',
            end: '2025-08-01T19:00:00',
            location: 'Meeting Room A',
            attendees: ['A', 'B', 'C'],
            category: 'time',
            state: 'Free',
            isReadOnly: false,
            color: '#ff4b2b',
            customStyle: {
                fontStyle: 'italic',
                fontSize: '15px',
            },
        },
        {
            id: '3',
            calendarId: 'live-stream',
            title: 'Battlefield',
            body: 'TOAST UI Calendar',
            start: '2025-08-01T17:00:00',
            end: '2025-08-01T19:00:00',
            location: 'Meeting Room A',
            attendees: ['A', 'B', 'C'],
            category: 'time',
            state: 'Free',
            isReadOnly: false,
            color: '#ff4b2b',
            customStyle: {
                fontStyle: 'italic',
                fontSize: '15px',
            },
        },
        {
            id: '4',
            calendarId: 'live-stream',
            title: 'Battlefield',
            body: 'TOAST UI Calendar',
            start: '2025-08-01T17:00:00',
            end: '2025-08-01T19:00:00',
            location: 'Meeting Room A',
            attendees: ['A', 'B', 'C'],
            category: 'time',
            state: 'Free',
            isReadOnly: false,
            color: '#ff4b2b',
            customStyle: {
                fontStyle: 'italic',
                fontSize: '15px',
            },
        },
        {
            id: '5',
            calendarId: 'live-stream',
            title: 'Battlefield',
            body: 'TOAST UI Calendar',
            start: '2025-08-01T17:00:00',
            end: '2025-08-01T19:00:00',
            location: 'Meeting Room A',
            attendees: ['A', 'B', 'C'],
            category: 'time',
            state: 'Free',
            isReadOnly: false,
            color: '#ff4b2b',
            customStyle: {
                fontStyle: 'italic',
                fontSize: '15px',
            },
        },
        {
            id: '6',
            calendarId: 'live-stream',
            title: 'Battlefield',
            body: 'TOAST UI Calendar',
            start: '2025-08-01T17:00:00',
            end: '2025-08-01T19:00:00',
            location: 'Meeting Room A',
            attendees: ['A', 'B', 'C'],
            category: 'time',
            state: 'Free',
            isReadOnly: false,
            color: '#ff4b2b',
            customStyle: {
                fontStyle: 'italic',
                fontSize: '15px',
            },
        },
        {
            id: '7',
            calendarId: 'live-stream',
            title: 'Battlefield',
            body: 'TOAST UI Calendar',
            start: '2025-08-01T17:00:00',
            end: '2025-08-01T19:00:00',
            location: 'Meeting Room A',
            attendees: ['A', 'B', 'C'],
            category: 'time',
            state: 'Free',
            isReadOnly: false,
            color: '#ff4b2b',
            customStyle: {
                fontStyle: 'italic',
                fontSize: '15px',
            },
        },
        {
            id: '8',
            calendarId: 'live-stream',
            title: 'Battlefield',
            body: 'TOAST UI Calendar',
            start: '2025-08-01T17:00:00',
            end: '2025-08-01T19:00:00',
            location: 'Meeting Room A',
            attendees: ['A', 'B', 'C'],
            category: 'time',
            state: 'Free',
            isReadOnly: false,
            color: '#ff4b2b',
            customStyle: {
                fontStyle: 'italic',
                fontSize: '15px',
            },
        }
    ]
}
